### ISSUE TITLE
Clipping on Unicode

### ISSUE THREAD

**Issue by dedisystems** [scottschiller/Snowstorm#36]
I have changed the Snow dot on my website to the 🍂 icon, this being accomplished with "🍂 (U+1F342)"
However, I cannot find the best setting for the pixels.
```html
			<script type="text/javascript">
				snowStorm.snowColor = '#DBFFFF'; // blue-ish snow!? < This is poinless if unicode icon present
				snowStorm.flakesMaxActive = 24;  // show more snow on screen at once
				snowStorm.animationInterval = 40; // Flakes Dropping Now
				snowStorm.useTwinkleEffect = true; // let the snow flicker in and out of view
				snowStorm.excludeMobile = false;  // Excludes mobile
				snowStorm.snowCharacter = '🍂'; // for fall 🍁🍂
				snowStorm.useMeltEffect = false; // Disable for fall
				snowStorm.flakeWidth = 11; // Fix Width clip
				snowStore.flakeHeight = 11; // Fix Height clip
			</script>
```
Changing the sizes any higher at all only widen 90% of the way, but I cannot get the height correct, any alternative?

This is the best I can get it by adjusting the flakes to very large pixels
![image](https://user-images.githubusercontent.com/43257146/48194237-14a3dd80-e312-11e8-95b4-9e338e60bce9.png)

**Comment by dedisystems** [comment]
![image](https://user-images.githubusercontent.com/43257146/48194480-c5aa7800-e312-11e8-8f2c-c395b567b1f4.png)
I'v atleast got width to work when its set to 900
```html
				snowStorm.flakeWidth = 900; // Fix Width clip
```
However, no matter what Height, it still shows the same height. Possibly a limitation? Maybe a work around?

**Comment by dedisystems** [comment]
Fixed my own issue, Quite simple fix. I forgot to go over my code and missed the spelling mistake on the 
snowStorm for the flake height, realized it was snowStore instead. Sorry bout that!

**Comment by scottschiller** [comment]
Ah-ha! Sorry, yes - you need to just fiddle with the flake width/height and you should be able to avoid the clipping issue there.

I realize US Thanksgiving is coming up soon, and it always around this time of year that people start downloading SnowStorm for all the Black Friday and holiday sales. 😬
