### ISSUE TITLE
dont randomize wind at each start

### ISSUE THREAD

**Issue by DanielRuf** [scottschiller/Snowstorm#9]
we dont need line #461 of `https://github.com/scottschiller/Snowstorm/blob/master/snowstorm.js` when we want to have the same wind parameters and use the settings of `vMaxX` and `vMaxY` so these values are not overwritten by the `s.randomizeWind();` at each start

**Comment by DekiGk** [comment]
When I get rid of the randomizeWind function my snow doesn`t work. Have you found a way to get rid of the random wind?

**Comment by DanielRuf** [comment]
@DekiGk This issue is quite old and I did not use Snowstorm since then. Do you have any errors in your browser console?

**Comment by scottschiller** [comment]
I should make this optional, but it's easy enough to have the individual velocity-setting just return the same values.

```
this.setVelocities = function() {
  s.vX = storm.vMaxX;
  s.vY = storm.vMaxY;
};
```

**Comment by DekiGk** [comment]
@scottschiller Thanks for this. I will try it out.
@DanielRuf no errors, just couldn`t get rid of the random wind :D
